language: python
python:
- pypy3
- pypy
- '3.6'
- '3.5'
- '3.4'
- '2.7'
sudo: false
install:
- pip install -U pip
- pip install -U -r requirements.txt
- pip install -U -r requirements-d.txt
- python ./setup.py develop
script:
- pytest tests/*
deploy:
  provider: pypi
  user: davidlday
  distributions: sdist bdist_wheel
  on:
    python: '3.6'
    tags: true

